### ISSUE TITLE
[Task]: Layout Design (Floor2)

### ISSUE THREAD

**Issue by rowanspain** [MULT154/GameProjectTemplate#2]
### Rubric Criteria

- [ ] Gameplay
- [ ] Graphics
- [X] Design
- [ ] User Experience
- [ ] Scripting
- [ ] Sound
- [ ] Quality
- [ ] Process

### Briefly, what are you going to work on?

Second level grayboxing and some prop storyboarding/concept art.

### Provide at least one example of a similiar element in another game.

Slenderman Sanatorium level design but not so scary and is a library.

https://www.indiedb.com/games/slendermans-shadow/downloads/sanatorium-v14

### What is needed to implement the task?

To model the basic layout of the second level using 3D shapes.

### What is the biggest risk it will not get done?

That I switch to prop design for some reason.

### How do I know it is ready? (Test case)

That it is not bugging or glitching or exploding, and is a completely stable model/layout to tread through. There would be an image available.

**Comment by rowanspain** [comment]
https://github.com/rowanspain/Level2_RSpain.git

**Comment by rowanspain** [comment]
![image](https://github.com/MULT154/GameProjectTemplate/assets/125788793/5c7d5647-c0a5-4117-9eb8-21e129771d10)

**Comment by rowanspain** [comment]
https://github.com/MULT154/GameProjectTemplate/assets/125788793/2ae6b2c6-b25b-434f-8043-1c016466ce3a

**Comment by SDMesaAssignments** [comment]
- For what you need to implement a few more details, Unity Editor, which 3D shapes, the ones within Unity or something else?
- For the risk analysis lets keep it to the task we are describing, even though what you suggested could be a bigger risk.
